# Controller configuration for fake execution
# Even with fake_execution: true, we need to define controller names
# so that trajectory_execution_manager knows which joints to "fake" control

controller_names:
  - fake_manipulator_controller
  - fake_gripper_controller

fake_manipulator_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - joint_7

fake_gripper_controller:
  type: GripperCommand
  action_ns: gripper_cmd
  default: true
  joints:
    - robotiq_85_left_knuckle_joint
